{"time":"2025-10-21T22:58:50.488938-04:00","level":"INFO","msg":"stream: starting","core version":"0.22.2"}
{"time":"2025-10-21T22:58:50.7731897-04:00","level":"INFO","msg":"stream: created new stream","id":"718f2gxr"}
{"time":"2025-10-21T22:58:50.7742611-04:00","level":"INFO","msg":"handler: started","stream_id":"718f2gxr"}
{"time":"2025-10-21T22:58:50.7779925-04:00","level":"INFO","msg":"stream: started","id":"718f2gxr"}
{"time":"2025-10-21T22:58:50.7785116-04:00","level":"INFO","msg":"writer: started","stream_id":"718f2gxr"}
{"time":"2025-10-21T22:58:50.7790816-04:00","level":"INFO","msg":"sender: started","stream_id":"718f2gxr"}
{"time":"2025-10-22T05:22:06.2045775-04:00","level":"INFO","msg":"api: retrying HTTP error","status":502,"url":"https://api.wandb.ai/files/trexxxxxxxxxxy-rl/rlgym-ppo/718f2gxr/file_stream","body":"\n<html><head>\n<meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\">\n<title>502 Server Error</title>\n</head>\n<body text=#000000 bgcolor=#ffffff>\n<h1>Error: Server Error</h1>\n<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>\n<h2></h2>\n</body></html>\n"}
{"time":"2025-10-22T09:03:16.2898165-04:00","level":"INFO","msg":"api: retrying HTTP error","status":502,"url":"https://api.wandb.ai/graphql","body":"\n<html><head>\n<meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\">\n<title>502 Server Error</title>\n</head>\n<body text=#000000 bgcolor=#ffffff>\n<h1>Error: Server Error</h1>\n<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>\n<h2></h2>\n</body></html>\n"}
{"time":"2025-10-22T09:43:15.2702603-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/trexxxxxxxxxxy-rl/rlgym-ppo/718f2gxr/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-22T10:11:15.2594098-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/trexxxxxxxxxxy-rl/rlgym-ppo/718f2gxr/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-22T10:28:45.2423561-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/trexxxxxxxxxxy-rl/rlgym-ppo/718f2gxr/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-22T11:57:15.2501816-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/trexxxxxxxxxxy-rl/rlgym-ppo/718f2gxr/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-22T11:57:38.7732467-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/trexxxxxxxxxxy-rl/rlgym-ppo/718f2gxr/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-22T12:50:06.0400019-04:00","level":"INFO","msg":"flowcontrol: backed up, offloading to disk","recordNumber":118248}
{"time":"2025-10-22T12:50:12.3799862-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 10.48.207.27:60722->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-22T12:50:14.7982004-04:00","level":"INFO","msg":"flowcontrol: unblocked","totalOffloaded":25}
{"time":"2025-10-22T13:05:50.8448311-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/trexxxxxxxxxxy-rl/rlgym-ppo/718f2gxr/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-22T13:06:14.1251524-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/trexxxxxxxxxxy-rl/rlgym-ppo/718f2gxr/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-22T17:59:04.6510296-04:00","level":"INFO","msg":"flowcontrol: backed up, offloading to disk","recordNumber":165110}
{"time":"2025-10-22T17:59:09.578465-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 10.48.207.27:55445->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-22T17:59:11.9740742-04:00","level":"INFO","msg":"flowcontrol: unblocked","totalOffloaded":27}
{"time":"2025-10-22T17:59:33.0079151-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/trexxxxxxxxxxy-rl/rlgym-ppo/718f2gxr/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-22T19:20:27.0268241-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/trexxxxxxxxxxy-rl/rlgym-ppo/718f2gxr/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-22T19:45:02.6397958-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/trexxxxxxxxxxy-rl/rlgym-ppo/718f2gxr/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-22T19:45:25.996018-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/trexxxxxxxxxxy-rl/rlgym-ppo/718f2gxr/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-22T20:21:08.8082591-04:00","level":"INFO","msg":"flowcontrol: backed up, offloading to disk","recordNumber":186368}
{"time":"2025-10-22T20:21:26.069198-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": context deadline exceeded"}
{"time":"2025-10-22T20:21:45.235861-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 10.48.207.27:62856->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-22T20:21:49.474797-04:00","level":"INFO","msg":"flowcontrol: unblocked","totalOffloaded":97}
